version: '3.8'

services:
  nginx:  
    image: nginx:latest
    ports:
    - '80:80'

    depends_on:
    - app
  

    volumes:
    - ./nginx.conf/nginx.conf:/etc/nginx/conf.d/default.conf


  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
     - app1_logs:/app/logs
    depends_on:
     db: 
        condition: service_healthy

    ports:
     - '5000'



  db:
    
    image: mysql:latest
    ports:
      - "3300:3306"
    environment: 
      - MYSQL_DATABASE=access_log
      - MYSQL_ROOT_PASSWORD=123456
    command: --default-authentication-plugin=mysql_native_password
    
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      interval: 5s
      retries: 5
    
    volumes:
      - dblogs:/var/log
      - dbdata:/var/lib/mysql
      


  
volumes:
  app1_logs:
  dbdata:
  dblogs:















